version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    target-branch: test
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /backend
    target-branch: test
    schedule: 
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    target-branch: test
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
