FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
COPY scripts/playwright-install.mjs scripts/
ENV PLAYWRIGHT_SKIP_INSTALL=1
RUN npm ci

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll=2000", "--proxy-config", "proxy.conf.docker.json"]
