version: "3.8"

services:
  api:
    build: null
    image: ghcr.io/company/demo-api:prod
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__RefreshCookieSecure: "true"

  frontend:
    build: null
    image: ghcr.io/company/demo-frontend:prod

  pgadmin:
    profiles:
      - tools