name: CI

on:
  pull_request:
    branches:
      - main
      - test
    paths:
      - "backend/**"
      - "frontend/**"
      - "backend.Tests/**"
      - ".github/workflows/**"
      - "BasicApp.sln"
  push:
    branches:
      - main
      - test
    paths:
      - "backend/**"
      - "frontend/**"
      - "backend.Tests/**"
      - ".github/workflows/**"
      - "BasicApp.sln"

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
